<?php

namespace Neoan3\Component\Header;

use Neoan3\Core\Unicore;

/**
 * Class HeaderController
 * @package Neoan3\Component\Header
 *
 * Generated by neoan3-cli for neoan3 v3.*
 */

class HeaderController extends Unicore{
    /**
     * Route: Header
     */
    function init(): void
    {
        $this
            ->uni('Demo')
            ->hook('main', 'header')
            ->output();
    }

}