<?php

namespace Neoan3\Component\Invite;

use Neoan3\Apps\Db;
use Neoan3\Frame\Demo;
use Neoan3\Model\User\UserModel;

/**
 * Class InviteController
 * @package Neoan3\Component\Invite
 *
 * Generated by neoan3-cli for neoan3 v3.*
 */

class InviteController extends Demo {
    /**
     * Route: Invite
     */
    function init(): void
    {
        $this
            ->hook('main', 'invite')
            ->output();
    }

    /**
     * @throws \Neoan3\Core\RouteException
     */
    function postInvite($body)
    {
        $teacher = $this->teacherOnly();
        $this->loadModel(UserModel::class);

        $found = UserModel::find(['email'=> $body['email']]);
        $password = false;
        // new user?
        if(empty($found)){
            $password = bin2hex(random_bytes(8));
            $student = UserModel::register(['email'=>$body['email'],'password'=>$password]);
        } else {
            $student = $found[0];
        }
        Db::ask('user_teacher', [
            'user_id' => '$'. $student['id'],
            'teacher_id' =>'$'.  $teacher['id']
        ]);
        return [
            'email'=> $body['email'],
            'password' => $password
        ];

    }


}