<?php
/* Generated by neoan3-cli */

namespace Neoan3\Model\User;

use Neoan3\Core\RouteException;
use Neoan3\Provider\MySql\Database;
use Neoan3\Provider\Model\Model;
use Neoan3\Provider\MySql\Transform;

/**
 * Class UserModel
 * @package Neoan3\Model\User
 * @method static get(string $id)
 * @method static create(array $modelArray)
 * @method static update(array $modelArray)
 * @method static find(array $conditionArray)
 * @method static delete(string $id, bool $hard = false)
 */

class UserModel implements Model{

    /**
     * @var Database|null
     */
    private static ?Database $db = null;

    /**
     * @param $method
     * @param $args
     * @return mixed
     */
    public static function __callStatic($method, $args)
    {
        if(!method_exists(self::class, $method)){
            $transform = new Transform('user', self::$db);
            return $transform->$method(...$args);
        } else {
            return self::$method(...$args);
        }
    }

    /**
     * @throws RouteException
     */
    public static function login($credentials)
    {
        $find = self::find(['email'=>$credentials['email']]);
        if(empty($find)){
            throw new RouteException('unauthorized',402);
        }
        if(!password_verify($credentials['password'], $find[0]['password'])){
            throw new RouteException('unauthorized',402);
        }
        return $find[0];
    }

    public static function register($credentials)
    {
        $credentials['password'] = '=' . password_hash($credentials['password'], PASSWORD_DEFAULT);
        return self::create($credentials);
    }

    /**
     * @param array $providers
     */
    public static function init(array $providers)
    {
        foreach ($providers as $key => $provider){
            if($key === 'db'){
                self::$db = $provider;
            }
        }
    }

}