<?php

namespace Neoan3\Component\Test;

use Neoan3\Frame\Demo;
use Neoan3\Model\Cloze\ClozeModel;

/**
 * Class TestController
 * @package Neoan3\Component\Test
 *
 * Generated by neoan3-cli for neoan3 v3.*
 */

class TestController extends Demo{

    function init()
    {
        $prefilled = ['test_text'=>'', 'answer_json'=>'', 'id'=>null, 'original'=>'', 'disclose'=>0];
        if(sub(1)){
            $this->loadModel(ClozeModel::class);
            $prefilled = ClozeModel::get(sub(1));
        }
        $this->hook('main','test', $prefilled);
        $this->output();
    }

    /**
    * GET: api.v1/test
    * GET: api.v1/test/{id}
    * GET: api.v1/test?{query-string}
    * @param string|null $id
    * @param array $params
    * @return array
    */
    function getTest(?string $id = null, array $params = []): array
    {
        $auth = $this->Auth->restrict();
        $this->loadModel(ClozeModel::class);
        if($id){
            ClozeModel::get($id);
        }
        if(isset($params['teacher_id'])){
            $params['teacher_id'] = '$'. $params['teacher_id'];
        }
        return ClozeModel::find($params);
    }

    /**
     * POST: api.v1/test
     * @param $body
     * @return array
     */
    function postTest(array $body): array
    {
        $auth = $this->Auth->restrict();
        $this->loadModel(ClozeModel::class);
        $body['teacher_id'] = $auth->getUserId();
        $body['answer_json'] = '='. json_encode($body['answer_json']);
        if(isset($body['id']) && !empty($body['id'])){
            return ClozeModel::update($body);
        }
        return ClozeModel::create($body);
    }
}
